# Generated by Django 5.2.1 on 2025-06-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersAuthApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('user_managment', 'User Managment'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
