# Generated by Django 5.2.1 on 2025-06-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersAuthApp', '0002_custompermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custompermission',
            options={'default_permissions': (), 'managed': False, 'permissions': (('user_managment', 'User Managment'), ('test_code', 'test Managment'))},
        ),
    ]
