# Generated by Django 5.2.1 on 2025-06-03 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersAuthApp', '0004_useraccount_address_useraccount_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custompermission',
            options={'default_permissions': (), 'managed': False, 'permissions': (('user_managment', 'User Managment'),)},
        ),
    ]
