# Generated by Django 5.2.1 on 2025-06-03 12:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersAuthApp', '0005_alter_custompermission_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='created_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='updated_data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
