# Generated by Django 5.2.1 on 2025-06-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersAuthApp', '0006_useraccount_created_data_useraccount_updated_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='created_data',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='updated_data',
            new_name='updated_date',
        ),
    ]
