# Generated by Django 5.2.1 on 2025-06-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersAuthApp', '0010_delete_activationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='last_password_reset_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
