# Generated by Django 5.2.1 on 2025-06-04 09:47

import systemSettingsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='My Company', max_length=255)),
                ('company_name_ar', models.CharField(default='شركتي', max_length=255)),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logo/', validators=[systemSettingsApp.models.validate_logo])),
                ('phone_number', models.CharField(default='', max_length=50)),
                ('fax_number', models.CharField(default='', max_length=50)),
                ('address', models.TextField(default='')),
                ('address_ar', models.TextField(default='')),
                ('reset_password_template_en', models.TextField(blank=True, null=True)),
                ('reset_password_template_ar', models.TextField(blank=True, null=True)),
                ('activation_email_template_en', models.TextField(blank=True, null=True)),
                ('activation_email_template_ar', models.TextField(blank=True, null=True)),
                ('email_host', models.CharField(blank=True, max_length=255, null=True)),
                ('email_port', models.PositiveIntegerField(blank=True, null=True)),
                ('email_host_user', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_host_password', models.CharField(blank=True, max_length=255, null=True)),
                ('email_use_tls', models.BooleanField(default=False)),
                ('email_use_ssl', models.BooleanField(default=False)),
                ('default_language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=2)),
                ('site_title', models.CharField(default='My App', max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('allow_user_registration', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
