# Generated by Django 5.2.1 on 2025-06-04 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemSettingsApp', '0002_remove_siteconfiguration_meta_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteConfiguration',
            new_name='MainConfiguration',
        ),
        migrations.AlterModelOptions(
            name='mainconfiguration',
            options={'verbose_name': 'main Configuration', 'verbose_name_plural': 'main Configuration'},
        ),
    ]
