# Generated by Django 5.2.1 on 2025-06-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemSettingsApp', '0003_rename_siteconfiguration_mainconfiguration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainconfiguration',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainconfiguration',
            name='address_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainconfiguration',
            name='fax_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mainconfiguration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
