# Generated by Django 5.2.1 on 2025-06-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemSettingsApp', '0004_alter_mainconfiguration_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainconfiguration',
            name='activation_email_template_ar',
            field=models.TextField(default='test1-test2'),
        ),
        migrations.AlterField(
            model_name='mainconfiguration',
            name='activation_email_template_en',
            field=models.TextField(default='test1-test2'),
        ),
        migrations.AlterField(
            model_name='mainconfiguration',
            name='address',
            field=models.TextField(default='test1-test2'),
        ),
        migrations.AlterField(
            model_name='mainconfiguration',
            name='address_ar',
            field=models.TextField(default='test1-test2'),
        ),
        migrations.AlterField(
            model_name='mainconfiguration',
            name='email_host',
            field=models.CharField(default='smtp.test.local', max_length=255),
        ),
        migrations.AlterField(
            model_name='mainconfiguration',
            name='email_host_password',
            field=models.CharField(default='00000000', max_length=255),
        ),
        migrations.AlterField(
            model_name='mainconfiguration',
            name='email_host_user',
            field=models.EmailField(default='user@test.local', max_length=254),
        ),
        migrations.AlterField(
            model_name='mainconfiguration',
            name='email_port',
            field=models.PositiveIntegerField(default=465),
        ),
        migrations.AlterField(
            model_name='mainconfiguration',
            name='fax_number',
            field=models.CharField(default='000000000', max_length=50),
        ),
        migrations.AlterField(
            model_name='mainconfiguration',
            name='phone_number',
            field=models.CharField(default='000000000', max_length=50),
        ),
        migrations.AlterField(
            model_name='mainconfiguration',
            name='reset_password_template_ar',
            field=models.TextField(default='test1-test2'),
        ),
        migrations.AlterField(
            model_name='mainconfiguration',
            name='reset_password_template_en',
            field=models.TextField(default='test1-test2'),
        ),
        migrations.AlterField(
            model_name='mainconfiguration',
            name='support_email',
            field=models.EmailField(default='supprt@test.local', max_length=254),
        ),
    ]
