# Generated by Django 5.2.1 on 2025-06-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemSettingsApp', '0005_alter_mainconfiguration_activation_email_template_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainconfiguration',
            name='allow_registration_without_email_verification',
            field=models.BooleanField(default=False),
        ),
    ]
