# Generated by Django 5.2.1 on 2025-06-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemSettingsApp', '0006_mainconfiguration_allow_registration_without_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainconfiguration',
            name='site_name',
            field=models.CharField(default='My Site Name', max_length=255),
        ),
        migrations.AddField(
            model_name='mainconfiguration',
            name='site_name_ar',
            field=models.CharField(default='اسم الموقع', max_length=255),
        ),
        migrations.AlterField(
            model_name='mainconfiguration',
            name='activation_email_template_ar',
            field=models.TextField(default='\n        مرحبًا {{full_name}}،\n\n        شكرًا لتسجيلك في {{site_name}}!\n\n        يرجى النقر على الرابط أدناه لتفعيل حسابك:\n\n        {{activation_link}}\n\n        إذا لم تقم بإنشاء هذا الحساب، يمكنك تجاهل هذه الرسالة.\n\n        مع تحيات،  \n        فريق {{company_name}}\n        '),
        ),
        migrations.AlterField(
            model_name='mainconfiguration',
            name='activation_email_template_en',
            field=models.TextField(default='\n        Hello {{full_name}},\n\n        Thank you for registering at {{site_name}}!\n\n        Please click the link below to activate your account:\n\n        {{activation_link}}\n\n        If you did not sign up for this account, please ignore this email.\n\n        Best regards,  \n        {{company_name}} Team\n        '),
        ),
        migrations.AlterField(
            model_name='mainconfiguration',
            name='company_name_ar',
            field=models.CharField(default='إسم الشركة', max_length=255),
        ),
        migrations.AlterField(
            model_name='mainconfiguration',
            name='reset_password_template_ar',
            field=models.TextField(default='\n        مرحبًا {{ full_name }},\n\n        لقد تلقينا طلبًا لإعادة تعيين كلمة المرور لحسابك في {{ site_name }}.\n\n        لإعادة تعيين كلمة المرور الخاصة بك، يرجى الضغط على الرابط أدناه:\n\n        {{ reset_link }}\n\n        إذا لم تطلب إعادة تعيين كلمة المرور، يمكنك تجاهل هذه الرسالة. ستبقى كلمة المرور الخاصة بك دون تغيير.\n\n        شكرًا لك،  \n        فريق {{ company_name }}\n        '),
        ),
        migrations.AlterField(
            model_name='mainconfiguration',
            name='reset_password_template_en',
            field=models.TextField(default='\n        Hello {{ full_name }},\n\n        We received a request to reset your password for your {{ site_name }} account.\n\n        To reset your password, click the link below:\n\n        {{ reset_link }}\n\n        If you didn’t request a password reset, you can ignore this email. Your password will remain unchanged.\n\n        Thank you,  \n        The {{ company_name }} Team\n        '),
        ),
    ]
