# Generated by Django 5.2.1 on 2025-06-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemSettingsApp', '0007_mainconfiguration_site_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainconfiguration',
            old_name='email_host',
            new_name='smtp_host',
        ),
        migrations.RenameField(
            model_name='mainconfiguration',
            old_name='email_host_user',
            new_name='smtp_host_user',
        ),
        migrations.RenameField(
            model_name='mainconfiguration',
            old_name='email_host_password',
            new_name='smtp_host_user_password',
        ),
        migrations.RenameField(
            model_name='mainconfiguration',
            old_name='email_port',
            new_name='smtp_port',
        ),
        migrations.RenameField(
            model_name='mainconfiguration',
            old_name='email_use_ssl',
            new_name='smtp_use_ssl',
        ),
        migrations.RenameField(
            model_name='mainconfiguration',
            old_name='email_use_tls',
            new_name='smtp_use_tls',
        ),
        migrations.AddField(
            model_name='mainconfiguration',
            name='frontend_activation_url',
            field=models.URLField(default='http://localhost:3000/account/activate-account', help_text='Base frontend URL for account activation, e.g. http://example.com/activate-account'),
        ),
    ]
