# Generated by Django 5.2.1 on 2025-06-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemSettingsApp', '0008_rename_email_host_mainconfiguration_smtp_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainconfiguration',
            name='reset_email_wait_hours',
            field=models.PositiveIntegerField(default=1, help_text='Minimum number of hours required between password reset emails for the same user.'),
        ),
    ]
