# Generated by Django 5.2.1 on 2025-06-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemSettingsApp', '0009_mainconfiguration_reset_email_wait_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainconfiguration',
            name='frontend_reset_password_url',
            field=models.URLField(default='http://localhost:3000/account/reset_password', help_text='Base frontend URL for reset_password, e.g. http://example.com/reset_password'),
        ),
    ]
