# Generated by Django 5.2.1 on 2025-06-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemSettingsApp', '0010_mainconfiguration_frontend_reset_password_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainconfiguration',
            name='is_captcha_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
