# Generated by Django 5.2.1 on 2025-06-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemSettingsApp', '0012_queuedemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queuedemail',
            old_name='error',
            new_name='error_message',
        ),
        migrations.AlterField(
            model_name='queuedemail',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=10),
        ),
    ]
