# Generated by Django 5.2.1 on 2025-06-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemSettingsApp', '0013_rename_error_queuedemail_error_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queuedemail',
            name='body',
        ),
        migrations.RemoveField(
            model_name='queuedemail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='queuedemail',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='queuedemail',
            name='is_html',
        ),
        migrations.RemoveField(
            model_name='queuedemail',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='queuedemail',
            name='status',
        ),
        migrations.RemoveField(
            model_name='queuedemail',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='queuedemail',
            name='to_email',
        ),
    ]
