# Generated by Django 5.2.1 on 2025-06-07 09:31

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemSettingsApp', '0014_remove_queuedemail_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuedemail',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queuedemail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queuedemail',
            name='is_html',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queuedemail',
            name='last_attempt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='queuedemail',
            name='max_retries',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='queuedemail',
            name='retries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queuedemail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='queuedemail',
            name='subject',
            field=models.CharField(default=datetime.datetime(2025, 6, 7, 9, 31, 47, 841574, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queuedemail',
            name='to_email',
            field=models.EmailField(default=datetime.datetime(2025, 6, 7, 9, 31, 53, 641521, tzinfo=datetime.timezone.utc), max_length=254),
            preserve_default=False,
        ),
    ]
