# Generated by Django 5.2.1 on 2025-06-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemSettingsApp', '0015_queuedemail_body_queuedemail_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuedemail',
            name='last_error_message',
            field=models.TextField(default=''),
        ),
    ]
