# Generated by Django 5.2.1 on 2025-06-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemSettingsApp', '0016_queuedemail_last_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuedemail',
            name='last_error_message_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
