# Generated by Django 5.2.1 on 2025-06-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemSettingsApp', '0017_queuedemail_last_error_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuedemail',
            name='last_error_message_date',
            field=models.DateTimeField(),
        ),
    ]
