# Generated by Django 5.2.1 on 2025-06-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemSettingsApp', '0018_alter_queuedemail_last_error_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuedemail',
            name='last_error_message_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
