# Generated by Django 5.2.1 on 2025-06-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemSettingsApp', '0019_alter_queuedemail_last_error_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuedemail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
