# Generated by Django 5.2.1 on 2025-05-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestEagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('sub_provider', 'sub_provider'), ('distributor ', 'distributor'), ('pos ', 'pos')], max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('city', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('received_request', 'received request'), ('replied_to_client ', 'replied to client ')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RequestService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('speed', models.CharField(choices=[('3', '3'), ('5', '5'), ('10', '10'), ('15', '15'), ('custom', 'Custom speed')], max_length=10)),
                ('custom_speed', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('received_request', 'received request'), ('replied_to_client ', 'replied to client ')], max_length=50)),
            ],
        ),
    ]
