# Generated by Django 5.2.1 on 2025-05-28 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyApplyApp', '0003_rename_requesteagent_requestagent_requestagentnote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedPackagePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.CharField(max_length=20)),
                ('speed_ar', models.CharField(max_length=20)),
                ('traffic_limit', models.CharField(max_length=20)),
                ('traffic_limit_ar', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficPackagePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traffic', models.CharField(max_length=20)),
                ('traffic_ar', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnlimitedSpeedTrafficPackagePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traffic', models.CharField(max_length=20)),
                ('traffic_ar', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='RequestAgentNote',
            new_name='RequestAgentPrivateNote',
        ),
        migrations.AlterField(
            model_name='requestagent',
            name='status',
            field=models.CharField(choices=[('received_request', 'received request'), ('replied_to_client ', 'replied to client ')], default='received_request', max_length=50),
        ),
        migrations.AlterField(
            model_name='requestservice',
            name='speed',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestservice',
            name='status',
            field=models.CharField(choices=[('received_request', 'received request'), ('replied_to_client', 'replied to client')], default='received_request', max_length=50),
        ),
        migrations.CreateModel(
            name='RequestServicePrivateNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='RequestServicePrivateNote_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RequestServiceNote',
        ),
    ]
