# Generated by Django 5.2.1 on 2025-05-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyApplyApp', '0005_requestagent_request_result_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestagent',
            name='created_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestservice',
            name='created_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
