# Generated by Django 5.2.1 on 2025-05-31 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyApplyApp', '0006_requestagent_created_ip_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestagent',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='requestservice',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='requestagentprivatenote',
            name='created_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestserviceprivatenote',
            name='created_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestagentprivatenote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RequestAgentNote_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestserviceprivatenote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RequestServicePrivateNote_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
