# Generated by Django 5.2.1 on 2025-05-31 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyApplyApp', '0007_alter_requestagent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestagentprivatenote',
            name='request_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RequestAgentPrivateNote_request_agent', to='easyApplyApp.requestagent'),
        ),
        migrations.AddField(
            model_name='requestserviceprivatenote',
            name='request_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RequestServicePrivateNote_RequestService', to='easyApplyApp.requestservice'),
        ),
    ]
