# Generated by Django 5.2.1 on 2025-06-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyApplyApp', '0009_requestagent_result_note_requestservice_result_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardLabelCheckRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.CharField(blank=True, default='', max_length=255)),
                ('title_ar', models.CharField(blank=True, default='', max_length=255)),
                ('details_ar', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CardLabelRequestAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.CharField(blank=True, default='', max_length=255)),
                ('title_ar', models.CharField(blank=True, default='', max_length=255)),
                ('details_ar', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CardLabelRequestService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.CharField(blank=True, default='', max_length=255)),
                ('title_ar', models.CharField(blank=True, default='', max_length=255)),
                ('details_ar', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CardLabelServicePrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.CharField(blank=True, default='', max_length=255)),
                ('title_ar', models.CharField(blank=True, default='', max_length=255)),
                ('details_ar', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
