# Generated by Django 5.2.1 on 2025-06-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyApplyApp', '0010_cardlabelcheckrequest_cardlabelrequestagent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppIndexTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('title_ar', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
