# Generated by Django 5.2.1 on 2025-06-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyApplyApp', '0011_appindextitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlabelcheckrequest',
            name='bootstrap_icon',
            field=models.CharField(blank=True, default='bi-wifi', max_length=100),
        ),
        migrations.AddField(
            model_name='cardlabelrequestagent',
            name='bootstrap_icon',
            field=models.CharField(blank=True, default='bi-wifi', max_length=100),
        ),
        migrations.AddField(
            model_name='cardlabelrequestservice',
            name='bootstrap_icon',
            field=models.CharField(blank=True, default='bi-wifi', max_length=100),
        ),
        migrations.AddField(
            model_name='cardlabelserviceprices',
            name='bootstrap_icon',
            field=models.CharField(blank=True, default='bi-wifi', max_length=100),
        ),
    ]
