# Generated by Django 5.2.1 on 2025-06-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyApplyApp', '0012_cardlabelcheckrequest_bootstrap_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestagent',
            name='area',
        ),
    ]
