# Generated by Django 5.2.1 on 2025-06-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyApplyApp', '0013_remove_requestagent_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestagent',
            name='business_type',
            field=models.CharField(choices=[('shop', 'Shop'), ('company ', 'Company')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
