# Generated by Django 5.2.1 on 2025-06-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyApplyApp', '0014_requestagent_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestagent',
            name='business_type',
            field=models.CharField(choices=[('shop', 'Shop'), ('company', 'Company')], max_length=50),
        ),
    ]
