# Generated by Django 5.2.1 on 2025-06-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyApplyApp', '0015_alter_requestagent_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestagent',
            name='agent_type',
            field=models.CharField(choices=[('sub_provider', 'sub_provider'), ('distributor', 'distributor'), ('pos', 'pos')], max_length=50),
        ),
    ]
