# Generated by Django 5.2.1 on 2025-06-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyApplyApp', '0016_alter_requestagent_agent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlabelrequestagent',
            name='request_form_sub_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cardlabelrequestagent',
            name='request_form_sub_title_ar',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cardlabelrequestagent',
            name='request_form_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cardlabelrequestagent',
            name='request_form_title_ar',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
