# Generated by Django 5.2.1 on 2025-06-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyApplyApp', '0018_cardlabelrequestservice_request_form_sub_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestservice',
            name='speed_package',
            field=models.JSONField(default=dict),
        ),
    ]
