# Generated by Django 5.2.1 on 2025-06-14 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyApplyApp', '0019_requestservice_speed_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestservice',
            name='custom_speed',
        ),
        migrations.RemoveField(
            model_name='requestservice',
            name='speed',
        ),
    ]
