# Generated by Django 5.2.1 on 2025-06-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyApplyApp', '0020_remove_requestservice_custom_speed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestservice',
            name='area',
        ),
    ]
