# Generated by Django 5.2.1 on 2025-06-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyApplyApp', '0021_remove_requestservice_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlabelcheckrequest',
            name='request_form_sub_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cardlabelcheckrequest',
            name='request_form_sub_title_ar',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cardlabelcheckrequest',
            name='request_form_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cardlabelcheckrequest',
            name='request_form_title_ar',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
