# Generated by Django 5.2.1 on 2025-06-14 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyApplyApp', '0023_requestagent_request_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestagent',
            old_name='request_type',
            new_name='type',
        ),
    ]
