# Generated by Django 5.2.1 on 2025-06-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyApplyApp', '0025_rename_request_type_requestservice_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPricesTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('title_hint', models.CharField(blank=True, default='', max_length=255)),
                ('title_hint_ar', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
