# Generated by Django 5.2.1 on 2025-06-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyApplyApp', '0026_apppricestitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppricestitle',
            name='title_ar',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
