# Generated by Django 5.2.1 on 2025-06-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyApplyApp', '0027_apppricestitle_title_ar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_page_title', models.CharField(blank=True, default='', max_length=255)),
                ('index_page_title_ar', models.CharField(blank=True, default='', max_length=255)),
                ('max_request_user_service', models.PositiveIntegerField(default=10, help_text='Max requests allowed per user servic , if 0 no limits ')),
                ('max_request_agent', models.PositiveIntegerField(default=10, help_text='Max requests allowed per agent, if 0 no limits')),
            ],
        ),
    ]
