# Generated by Django 5.2.1 on 2025-06-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyApplyApp', '0029_alter_requestagent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestservice',
            name='status',
            field=models.CharField(choices=[('pinding', 'Pinding'), ('complated', 'Complated')], default='pinding', max_length=50),
        ),
    ]
