# Generated by Django 5.2.1 on 2025-06-15 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyApplyApp', '0031_remove_requestagent_request_result_note_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppIndexTitle',
        ),
    ]
